# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2dfb48663f7a619164a3099a40828b9a070508940fcb0a12b6ab726f516cadd4a4a78e79a451d2c7a74da16d7d2f5a0b159ee8030ece12601d099121c3b121a

test:
  secret_key_base: 9fdcb16cca2e3555ac6a677869b542a6082f46ff7cb161d3d00d080f162e02f012ce85e9975b8da305b7265cc2410823cc1ded32cc611ddb54cfa17cf37850c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
